import requests
from bs4 import BeautifulSoup
import pandas as pd
from tqdm import tqdm
import time
import re

headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'
}

def extract_measurements(description):
    medidas = {'S': {}, 'M': {}, 'L': {}}
    current_size = None
    
    for line in description.split('\n'):
        line = line.strip()
        if line in ('S', 'M', 'L'):
            current_size = line
        elif current_size and ':' in line:
            key, value = [part.strip() for part in line.split(':', 1)]
            medidas[current_size][key] = value
    
    return medidas

def scrape_product(url):
    try:
        response = requests.get(url, headers=headers, timeout=10)
        
        # Manejar páginas no encontradas
        if response.status_code == 404:
            return {
                'URL': url,
                'Error': '404 - Producto no existe'
            }
            
        response.raise_for_status()
        soup = BeautifulSoup(response.text, 'html.parser')
        
        name = soup.find('h1', class_='product-title').get_text(strip=True) if soup.find('h1', class_='product-title') else 'No encontrado'
        price = soup.find('span', class_='price').get_text(strip=True) if soup.find('span', class_='price') else 'No encontrado'
        
        description_div = soup.find('div', class_='product-description user-content')
        description = description_div.get_text('\n', strip=True) if description_div else 'No encontrado'
        
        medidas = extract_measurements(description) if description_div else {}
        
        materiales = []
        if description_div:
            for p in description_div.find_all('p'):
                if 'material' in p.get_text().lower():
                    materiales.append(p.get_text(strip=True))
        
        return {
            'URL': url,
            'Nombre': name,
            'Precio': price,
            'Descripción': re.sub(r'\s+', ' ', description),
            'Materiales': ', '.join(materiales) if materiales else 'No especificado',
            'Medidas S': medidas.get('S', {}),
            'Medidas M': medidas.get('M', {}),
            'Medidas L': medidas.get('L', {}),
            'Tallas disponibles': list(medidas.keys()) if medidas else []
        }
        
    except Exception as e:
        print(f"Error en {url}: {str(e)}")
        return {
            'URL': url,
            'Error': str(e)
        }

if __name__ == "__main__":
    
# Tu lista de URLs aquí
    urls = [
        "https://www.imanofficial.com/productos/campera-hailey/",
        "https://www.imanofficial.com/productos/tapado-soft-largo1/",
        "https://www.imanofficial.com/productos/bufanda-glen/",
        "https://www.imanofficial.com/productos/tapado-soft-corto2/",
        "https://www.imanofficial.com/productos/tapado-soft-corto1/",
        "https://www.imanofficial.com/productos/vestido-trim-wild/",
        "https://www.imanofficial.com/productos/corpino-simone/",
        "https://www.imanofficial.com/productos/vestido-zaira/",
        "https://www.imanofficial.com/productos/vestido-triangle/",
        "https://www.imanofficial.com/productos/top-trim-wild/",
        "https://www.imanofficial.com/productos/vestido-verona/",
        "https://www.imanofficial.com/productos/top-polera-simone/",
        "https://www.imanofficial.com/productos/vestido-saas/",
        "https://www.imanofficial.com/productos/remera-v/",
        "https://www.imanofficial.com/productos/top-lux/",
        "https://www.imanofficial.com/productos/gorro-de-piel/",
        "https://www.imanofficial.com/productos/vestido-trim-lux/",
        "https://www.imanofficial.com/productos/falda-sun/",
        "https://www.imanofficial.com/productos/top-polera-trim/",
        "https://www.imanofficial.com/productos/bombacha-simone/",
        "https://www.imanofficial.com/productos/falda-amy/",
        "https://www.imanofficial.com/productos/top-sun/",
        "https://www.imanofficial.com/productos/vestido-kenia/",
        "https://www.imanofficial.com/productos/falda-vinil-strong/",
        "https://www.imanofficial.com/productos/chaleco-tom/",
        "https://www.imanofficial.com/productos/top-stripe/",
        "https://www.imanofficial.com/productos/chomba-brush/",
        "https://www.imanofficial.com/productos/vestido-ascot/",
        "https://www.imanofficial.com/productos/top-rain/",
        "https://www.imanofficial.com/productos/top-stormie/",
        "https://www.imanofficial.com/productos/vestido-gun/",
        "https://www.imanofficial.com/productos/vestido-siena/",
        "https://www.imanofficial.com/productos/vestido-trim/",
        "https://www.imanofficial.com/productos/polera-eme/",
        "https://www.imanofficial.com/productos/pantalon-tom/",
        "https://www.imanofficial.com/productos/top-closed/",
        "https://www.imanofficial.com/productos/top-boat/",
        "https://www.imanofficial.com/productos/body-loud1/",
        "https://www.imanofficial.com/productos/vestido-wavy/",
        "https://www.imanofficial.com/productos/blazer-tom/",
        "https://www.imanofficial.com/productos/falda-tom/",
        "https://www.imanofficial.com/productos/trench-rainproof/",
        "https://www.imanofficial.com/productos/body-basic/",
        "https://www.imanofficial.com/productos/babytee-clipped/",
        "https://www.imanofficial.com/productos/vestido-tokyo/",
        "https://www.imanofficial.com/productos/crop-top-low-cut/",
        "https://www.imanofficial.com/productos/body-lace/",
        "https://www.imanofficial.com/productos/top-scarf/",
        "https://www.imanofficial.com/productos/pantalon-strong1/",
        "https://www.imanofficial.com/productos/campera-strong/",
        "https://www.imanofficial.com/productos/falda-strong1/",
        "https://www.imanofficial.com/productos/tapado-glen/",
        "https://www.imanofficial.com/productos/jean-megan/",
        "https://www.imanofficial.com/productos/polera-estocolmo/",
        "https://www.imanofficial.com/productos/vestido-brush/",
        "https://www.imanofficial.com/productos/remera-button-ml/",
        "https://www.imanofficial.com/productos/pantalon-suede/",
        "https://www.imanofficial.com/productos/blazer-suede/",
        "https://www.imanofficial.com/productos/falda-midi-suede/",
        "https://www.imanofficial.com/productos/chaleco-suede/",
        "https://www.imanofficial.com/productos/falda-suede/",
        "https://www.imanofficial.com/productos/trench-suede/",
        "https://www.imanofficial.com/productos/pantalon-bugatti/",
        "https://www.imanofficial.com/productos/campera-bugatti/",
        "https://www.imanofficial.com/productos/falda-glen/",
        "https://www.imanofficial.com/productos/blazer-glen/",
        "https://www.imanofficial.com/productos/campera-aspen1/",
        "https://www.imanofficial.com/productos/campera-cat/",
        "https://www.imanofficial.com/productos/campera-brown/",
        "https://www.imanofficial.com/productos/tapado-ocicat/",
        "https://www.imanofficial.com/productos/musculosa-estocolmo/",
        "https://www.imanofficial.com/productos/remera-neck-mc/",
        "https://www.imanofficial.com/productos/remera-neck-ml/",
        "https://www.imanofficial.com/productos/pantalon-dakota/",
        "https://www.imanofficial.com/productos/sweater-dakota/",
        "https://www.imanofficial.com/productos/sweater-ophelia/",
        "https://www.imanofficial.com/productos/sweater-piper/",
        "https://www.imanofficial.com/productos/sweater-nina/",
        "https://www.imanofficial.com/productos/musculosa-eme-n2/",
        "https://www.imanofficial.com/productos/falda-button/",
        "https://www.imanofficial.com/productos/chaleco-button/",
        "https://www.imanofficial.com/productos/calza-zipper/",
        "https://www.imanofficial.com/productos/remera-brush-ml/",
        "https://www.imanofficial.com/productos/pantalon-brush/",
        "https://www.imanofficial.com/productos/polera-brush/",
        "https://www.imanofficial.com/productos/jogging-dukati/",
        "https://www.imanofficial.com/productos/vestido-mini-combinado/",
        "https://www.imanofficial.com/productos/babytee-rayada/",
        "https://www.imanofficial.com/productos/vestido-stripe1/",
        "https://www.imanofficial.com/productos/vestido-strapless-kayla-corto-enagua/",
        "https://www.imanofficial.com/productos/vestido-kayla-off-shoulders/",
        "https://www.imanofficial.com/productos/remera-bunny/",
        "https://www.imanofficial.com/productos/babytee-fruit/",
        "https://www.imanofficial.com/productos/babytee-cosmopolitan/",
        "https://www.imanofficial.com/productos/babytee-flower/",
        "https://www.imanofficial.com/productos/babytee-imantada/",
        "https://www.imanofficial.com/productos/remera-strawberry1/",
        "https://www.imanofficial.com/productos/remera-garnetfruit/",
        "https://www.imanofficial.com/productos/babytee-cotton/",
        "https://www.imanofficial.com/productos/vestido-mini-wild-cristal/",
        "https://www.imanofficial.com/productos/blusa-zebra-cristal/",
        "https://www.imanofficial.com/productos/vestido-flowers-con-mini-fallas/",
        "https://www.imanofficial.com/productos/vestido-ariel/",
        "https://www.imanofficial.com/productos/vestido-eme-cotton/",
        "https://www.imanofficial.com/productos/vestido-capri/",
        "https://www.imanofficial.com/productos/top-lino/",
        "https://www.imanofficial.com/productos/top-bra-con-corpino-incluido/",
        "https://www.imanofficial.com/productos/top-kim/",
        "https://www.imanofficial.com/productos/remera-desire/",
        "https://www.imanofficial.com/productos/remera-kim-manga-corta/",
        "https://www.imanofficial.com/productos/vestido-gold/",
        "https://www.imanofficial.com/productos/vestido-wild-cristal/",
        "https://www.imanofficial.com/productos/blusa-wild-cristal/",
        "https://www.imanofficial.com/productos/pantalon-wild-microtul1/",
        "https://www.imanofficial.com/productos/falda-gabardina/",
        "https://www.imanofficial.com/productos/pantalon-gabardina/",
        "https://www.imanofficial.com/productos/musculosa-eme-combinada/",
        "https://www.imanofficial.com/productos/pantalon-nix/",
        "https://www.imanofficial.com/productos/vestido-mini-strapples-owens/",
        "https://www.imanofficial.com/productos/vestido-balloon/",
        "https://www.imanofficial.com/productos/falda-kayla-picos/",
        "https://www.imanofficial.com/productos/musculosa-kayla1/",
        "https://www.imanofficial.com/productos/chaleco-wild/",
        "https://www.imanofficial.com/productos/top-volados-canoa1/",
        "https://www.imanofficial.com/productos/bermuda-kanye/",
        "https://www.imanofficial.com/productos/top-kate-asimetrico/",
        "https://www.imanofficial.com/productos/bermuda-scott/",
        "https://www.imanofficial.com/productos/musculosa-kim-reloaded/",
        "https://www.imanofficial.com/productos/pantalon-lino/",
        "https://www.imanofficial.com/productos/bando-greek-vol-2/",
        "https://www.imanofficial.com/productos/vestido-mini-zebra-cristal/",
        "https://www.imanofficial.com/productos/top-nix-diagonal/",
        "https://www.imanofficial.com/productos/vestido-aurora1/",
        "https://www.imanofficial.com/productos/vestido-alexa/",
        "https://www.imanofficial.com/productos/chaleco-linen/",
        "https://www.imanofficial.com/productos/vestido-aurora/",
        "https://www.imanofficial.com/productos/vestido-lino-largo/",
        "https://www.imanofficial.com/productos/vestido-delfin-strapples/",
        "https://www.imanofficial.com/productos/vestido-delfin/",
        "https://www.imanofficial.com/productos/vestido-delfin-corto/",
        "https://www.imanofficial.com/productos/falda-balloon/",
        "https://www.imanofficial.com/productos/chaleco-gabardina/",
        "https://www.imanofficial.com/productos/bermuda-animal-print/",
        "https://www.imanofficial.com/productos/bermuda-gabardina/",
        "https://www.imanofficial.com/productos/pantalon-broderi/",
        "https://www.imanofficial.com/productos/remera-cotton-ranglan/",
        "https://www.imanofficial.com/productos/musculosa-cotton/",
        "https://www.imanofficial.com/productos/vestido-brigerton-corto/",
        "https://www.imanofficial.com/productos/vestido-kate/",
        "https://www.imanofficial.com/productos/bermuda-kate/",
        "https://www.imanofficial.com/productos/chaleco-kate/",
        "https://www.imanofficial.com/productos/pantalon-kate/",
        "https://www.imanofficial.com/productos/pantalon-kate-wide/",
        "https://www.imanofficial.com/productos/falda-kate/",
        "https://www.imanofficial.com/productos/remera-cotton1/",
        "https://www.imanofficial.com/productos/remera-cotton/",
        "https://www.imanofficial.com/productos/blazer-crop-kate/",
        "https://www.imanofficial.com/productos/blazer-over-kate/",
        "https://www.imanofficial.com/productos/pantalon-poplin/",
        "https://www.imanofficial.com/productos/short-poplin/",
        "https://www.imanofficial.com/productos/vestido-poplin/",
        "https://www.imanofficial.com/productos/top-kim-off-shoulder/",
        "https://www.imanofficial.com/productos/polera-kim/",
        "https://www.imanofficial.com/productos/musculosa-lace/",
        "https://www.imanofficial.com/productos/vestido-skims-corto/",
        "https://www.imanofficial.com/productos/vestido-strapples-kayla/",
        "https://www.imanofficial.com/productos/top-kayla-off/",
        "https://www.imanofficial.com/productos/falda-greek-vol-2/",
        "https://www.imanofficial.com/productos/vestido-circle/",
        "https://www.imanofficial.com/productos/vestido-ballet/",
        "https://www.imanofficial.com/productos/vestido-skims/",
        "https://www.imanofficial.com/productos/body-kayla-frunce/",
        "https://www.imanofficial.com/productos/vestido-kayla-drapeado/",
        "https://www.imanofficial.com/productos/vestido-carrie/",
        "https://www.imanofficial.com/productos/remera-kim-oval/",
        "https://www.imanofficial.com/productos/pantalon-wild/",
        "https://www.imanofficial.com/productos/remera-kim-manga-larga/",
        "https://www.imanofficial.com/productos/pantalon-iggy/",
        "https://www.imanofficial.com/productos/vestido-simone/",
        "https://www.imanofficial.com/productos/bando-simone/",
        "https://www.imanofficial.com/productos/trench-iggy/",
        "https://www.imanofficial.com/productos/vestido-sakura/",
        "https://www.imanofficial.com/productos/body-simone/",
        "https://www.imanofficial.com/productos/falda-simone/",
        "https://www.imanofficial.com/productos/calza-simone/",
        "https://www.imanofficial.com/productos/body-oval/",
        "https://www.imanofficial.com/productos/musculosa-kim-preventa-semana-de-entrega-29-04/",
        "https://www.imanofficial.com/productos/vestido-kim-polera/",
        "https://www.imanofficial.com/productos/blazer-crash/",
        "https://www.imanofficial.com/productos/body-kayla/",
        "https://www.imanofficial.com/productos/vestido-greta/",
        "https://www.imanofficial.com/productos/body-swing/",
        "https://www.imanofficial.com/productos/mini-falda-wash/",
        "https://www.imanofficial.com/productos/campera-wash/",
        "https://www.imanofficial.com/productos/pantalon-cargo-silver/",
        "https://www.imanofficial.com/productos/blazer-sereia/",
        "https://www.imanofficial.com/productos/body-gaia-saas/",
        "https://www.imanofficial.com/productos/mini-crash/",
        "https://www.imanofficial.com/productos/pantalon-amy-sastrero/",
        "https://www.imanofficial.com/productos/polera-kayla/",
        "https://www.imanofficial.com/productos/vestido-kayla-largo/",
        "https://www.imanofficial.com/productos/baby-tee-ranglan/",
        "https://www.imanofficial.com/productos/campera-bomber-roy/",
        "https://www.imanofficial.com/productos/body-back/",
        "https://www.imanofficial.com/productos/vestido-dion/",
        "https://www.imanofficial.com/productos/saco-amy/",
        "https://www.imanofficial.com/productos/top-kayla-polera/",
        "https://www.imanofficial.com/productos/corset-west2/",
        "https://www.imanofficial.com/productos/vestido-puntilla-canoa/",
        "https://www.imanofficial.com/productos/vestido-mini-microtul/",
        "https://www.imanofficial.com/productos/jean-recto-brown/",
        "https://www.imanofficial.com/productos/jean-recto/",
        "https://www.imanofficial.com/productos/jean-skater/",
        "https://www.imanofficial.com/productos/jean-wide/",
        "https://www.imanofficial.com/productos/top-corset-crash/",
        "https://www.imanofficial.com/productos/pantalon-crash/",
        "https://www.imanofficial.com/productos/pantalon-nirvana1/",
        "https://www.imanofficial.com/productos/pantalon-wash/",
        "https://www.imanofficial.com/productos/pantalon-roy/",
        "https://www.imanofficial.com/productos/body-alexa1/",
        "https://www.imanofficial.com/productos/musculosa/",
        "https://www.imanofficial.com/productos/body-u-kayla1/",
        "https://www.imanofficial.com/productos/body-u-kayla/",
        "https://www.imanofficial.com/productos/vestido-shoulder/",
        "https://www.imanofficial.com/productos/vestido-kayla/",
        "https://www.imanofficial.com/productos/falda-crooc/",
        "https://www.imanofficial.com/productos/pantalon-north/",
        "https://www.imanofficial.com/productos/top-formy/",
        "https://www.imanofficial.com/productos/mini-falda-formy/",
        "https://www.imanofficial.com/productos/vestido-roma1/",
        "https://www.imanofficial.com/productos/jogging-essential/",
        "https://www.imanofficial.com/productos/hoddie-zipper/",
        "https://www.imanofficial.com/productos/tapado-emuna/",
        "https://www.imanofficial.com/productos/tapado-eternity/",
        "https://www.imanofficial.com/productos/blusa-black/",
        "https://www.imanofficial.com/productos/blusa-indigo/",
        "https://www.imanofficial.com/productos/camisa-nix/",
        "https://www.imanofficial.com/productos/top-nix/",
        "https://www.imanofficial.com/productos/camisa-eclipse/",
        "https://www.imanofficial.com/productos/pantalon-zipper/",
        "https://www.imanofficial.com/productos/pantalon-eclipse/",
        "https://www.imanofficial.com/productos/falda-bardot/",
        "https://www.imanofficial.com/productos/top-stone-bordado/",
        "https://www.imanofficial.com/productos/bomber-net/",
        "https://www.imanofficial.com/productos/bomber-net-bordada/",
        "https://www.imanofficial.com/productos/sweater-crop/",
        "https://www.imanofficial.com/productos/vestido-west-corto/",
        "https://www.imanofficial.com/productos/falda-moon/",
        "https://www.imanofficial.com/productos/campera-moon/",
        "https://www.imanofficial.com/productos/tapado-sky/",
        "https://www.imanofficial.com/productos/top-bardot1/",
        "https://www.imanofficial.com/productos/top-bardot/",
        "https://www.imanofficial.com/productos/vestido-west-midi/",
        "https://www.imanofficial.com/productos/pantalon-stripe-gris/",
        "https://www.imanofficial.com/productos/pantalon-amy/",
        "https://www.imanofficial.com/productos/pantalon-bardot/",
        "https://www.imanofficial.com/productos/musculosa-padme/",
        "https://www.imanofficial.com/productos/pantalon-gema/",
        "https://www.imanofficial.com/productos/musculosa-basic/",
        "https://www.imanofficial.com/productos/vestido-mini-owens/",
        "https://www.imanofficial.com/productos/vestido-jazmin/",
        "https://www.imanofficial.com/productos/top-habana1/",
        "https://www.imanofficial.com/productos/top-habana/",
        "https://www.imanofficial.com/productos/vestido-frunce-habana/",
        "https://www.imanofficial.com/productos/falda-midi-bruna/",
        "https://www.imanofficial.com/productos/vestido-cut-out-bling/",
        "https://www.imanofficial.com/productos/vestido-canoa/",
        "https://www.imanofficial.com/productos/body-off-shoulders/",
        "https://www.imanofficial.com/productos/falda-layla/",
        "https://www.imanofficial.com/productos/short-moon/",
        "https://www.imanofficial.com/productos/camisa-jazmin/",
        "https://www.imanofficial.com/productos/top-jazmin/",
        "https://www.imanofficial.com/productos/pantalon-cargo-crochet/",
        "https://www.imanofficial.com/productos/short-bresh-crochet/",
        "https://www.imanofficial.com/productos/falda-mini-owens/",
        "https://www.imanofficial.com/productos/top-victoria/",
        "https://www.imanofficial.com/productos/vestido-gaia1/",
        "https://www.imanofficial.com/productos/top-frunce-owens/",
        "https://www.imanofficial.com/productos/babytee-kim/",
        "https://www.imanofficial.com/productos/bikini-bombacha-blossom/",
        "https://www.imanofficial.com/productos/bikini-sunset-bombacha-vedetina/",
        "https://www.imanofficial.com/productos/bikini-bombacha-sunset/",
        "https://www.imanofficial.com/productos/bombacha-bikini-vedetina-heat-lilac/",
        "https://www.imanofficial.com/productos/bombacha-bikini-aruba/",
        "https://www.imanofficial.com/productos/bombacha-bikini-faces/",
        "https://www.imanofficial.com/productos/bombacha-bikini-basic1/",
        "https://www.imanofficial.com/productos/corpino-bikini-basic/",
        "https://www.imanofficial.com/productos/bikini-layla/",
        "https://www.imanofficial.com/productos/short-joana/",
        "https://www.imanofficial.com/productos/campera-joana/",
        "https://www.imanofficial.com/productos/vestido-shine-preventa-semana-de-entrega/",
        "https://www.imanofficial.com/productos/vestido-gaia/",
        "https://www.imanofficial.com/productos/top-arianna/",
        "https://www.imanofficial.com/productos/vestido-belly/",
        "https://www.imanofficial.com/productos/vestido-dreaming/",
        "https://www.imanofficial.com/productos/corset-west/",
        "https://www.imanofficial.com/productos/babytee-rayas1/",
        "https://www.imanofficial.com/productos/vestido-owens/",
        "https://www.imanofficial.com/productos/bermuda-gema/",
        "https://www.imanofficial.com/productos/culotte-moon/",
        "https://www.imanofficial.com/productos/vestido-marruecos/",
        "https://www.imanofficial.com/productos/top-nice/",
        "https://www.imanofficial.com/productos/top-bali/",
        "https://www.imanofficial.com/productos/falda-bali/",
        "https://www.imanofficial.com/productos/vestido-bali-tejido/",
        "https://www.imanofficial.com/productos/falda-killer3/",
        "https://www.imanofficial.com/productos/short-camp/",
        "https://www.imanofficial.com/productos/musculosa-luxe/",
        "https://www.imanofficial.com/productos/campera-camp/",
        "https://www.imanofficial.com/productos/top-puntilla-alexa/",
        "https://www.imanofficial.com/productos/top-rivera/",
        "https://www.imanofficial.com/productos/corset-bruna/",
        "https://www.imanofficial.com/productos/musculosa-eme/",
        "https://www.imanofficial.com/productos/body-alexa/",
        "https://www.imanofficial.com/productos/corset-toxic/",
        "https://www.imanofficial.com/productos/vestido-barbie-fecha-de-entrega-semana-14-08/",
        "https://www.imanofficial.com/productos/pantalon-galilei2/",
        "https://www.imanofficial.com/productos/chaleco-habana-fecha-de-entrega-semana/",
        "https://www.imanofficial.com/productos/falda-habana/",
        "https://www.imanofficial.com/productos/vestido-habana/",
        "https://www.imanofficial.com/productos/cargo-dua-zipper-fecha-de-entrega-semana-28-08/",
        "https://www.imanofficial.com/productos/top-corset-alexa-fecha-de-entrega-semana-28-08/",
        "https://www.imanofficial.com/productos/top-bang/",
        "https://www.imanofficial.com/productos/camisa-dua-fecha-de-entrega-semana-28-08/",
        "https://www.imanofficial.com/productos/top-moon-fecha-de-entrega-semana-28-08/",
        "https://www.imanofficial.com/productos/pantalon-chita/",
        "https://www.imanofficial.com/productos/top-diagonal-margot-fecha-de-entrega-semana-04-09/",
        "https://www.imanofficial.com/productos/pantalon-camp-fecha-de-entrega-semana-21-08/",
        "https://www.imanofficial.com/productos/top-tiras-alexa-fecha-de-entrega-semana-14-08/",
        "https://www.imanofficial.com/productos/falda-camp-fecha-de-entrega-semana-21-08/",
        "https://www.imanofficial.com/productos/vestido-toxic-fecha-de-entrega-semana-18-09/",
        "https://www.imanofficial.com/productos/top-margot-fecha-de-entrega-semana-14-08/",
        "https://www.imanofficial.com/productos/cargo-dua-pocket-fecha-de-entrega-semana-21-08/",
        "https://www.imanofficial.com/productos/campera-dua-fecha-de-entrega-semana-04-09/",
        "https://www.imanofficial.com/productos/vestido-margot-fecha-de-entrega-semana-14-08/",
        "https://www.imanofficial.com/productos/remera-margot-fecha-de-entrega-semana-21-08/",
        "https://www.imanofficial.com/productos/vestido-cut-out-toxic/",
        "https://www.imanofficial.com/productos/corset-gigi-fecha-de-entrega/",
        "https://www.imanofficial.com/productos/blazer-brisho-fecha-de-entrega-semana-28-08/",
        "https://www.imanofficial.com/productos/vestido-roma/",
        "https://www.imanofficial.com/productos/vestido-ibiza-fecha-de-entrega-semana-14-08/",
        "https://www.imanofficial.com/productos/vestido-reflex/",
        "https://www.imanofficial.com/productos/pantalon-toxic/",
        "https://www.imanofficial.com/productos/top-corpino-rayado/",
        "https://www.imanofficial.com/productos/blazer-croco-doble2/",
        "https://www.imanofficial.com/productos/vestido-prix3/",
        "https://www.imanofficial.com/productos/puffer-maiden/",
        "https://www.imanofficial.com/productos/remera/",
        "https://www.imanofficial.com/productos/blazer-mariposa5/",
        "https://www.imanofficial.com/productos/camisa-toxic/",
        "https://www.imanofficial.com/productos/top-dukati1/",
        "https://www.imanofficial.com/productos/falda-dukati1/",
        "https://www.imanofficial.com/productos/body-gaia/",
        "https://www.imanofficial.com/productos/babucha-cross-cuero-ovino3/",
        "https://www.imanofficial.com/productos/buzo-dukati/",
        "https://www.imanofficial.com/productos/remera-angel/",
        "https://www.imanofficial.com/productos/blazer-tapado-daytona/",
        "https://www.imanofficial.com/productos/pantalon-cavali-recto8/",
        "https://www.imanofficial.com/productos/pantalon-galilei/",
        "https://www.imanofficial.com/productos/top-romeo/",
        "https://www.imanofficial.com/productos/blazer-monet/",
        "https://www.imanofficial.com/productos/blazer-doble/",
        "https://www.imanofficial.com/productos/pantalon-reflex1/",
        "https://www.imanofficial.com/productos/pantalon-fornite/",
        "https://www.imanofficial.com/productos/blazer-ameli/",
        "https://www.imanofficial.com/productos/pantalon-galilei1/",
        "https://www.imanofficial.com/productos/joggin-reality/",
        "https://www.imanofficial.com/productos/joggin-penny/",
        "https://www.imanofficial.com/productos/pantalon-heavy1/",
        "https://www.imanofficial.com/productos/campera-cross-cuero1/",
        "https://www.imanofficial.com/productos/saco-bomber-cloud/",
        "https://www.imanofficial.com/productos/corpino-heavy1/",
        "https://www.imanofficial.com/productos/body-scorpion/",
        "https://www.imanofficial.com/productos/falda-midi-heavy/",
        "https://www.imanofficial.com/productos/blazer-vestido-maiden1/",
        "https://www.imanofficial.com/productos/blazer-entallado1/",
        "https://www.imanofficial.com/productos/falda-maiden4/",
        "https://www.imanofficial.com/productos/pantalon-cavali-wide-leg10/",
        "https://www.imanofficial.com/productos/bermuda-jade-lila/",
        "https://www.imanofficial.com/productos/blusa-cavali/",
        "https://www.imanofficial.com/productos/conjunto-bikini-emily/",
        "https://www.imanofficial.com/productos/conjunto-bikini-heat-lilac/",
        "https://www.imanofficial.com/productos/blazer-maiden1/",
        "https://www.imanofficial.com/productos/short-maiden2/",
        "https://www.imanofficial.com/productos/corset-maiden4/",
        "https://www.imanofficial.com/productos/falda-galilei/",
        "https://www.imanofficial.com/productos/vestido-maiden2/",
        "https://www.imanofficial.com/productos/camisa-heavy3/",
        "https://www.imanofficial.com/productos/blazer-holi1/",
        "https://www.imanofficial.com/productos/falda-diamond4/",
        "https://www.imanofficial.com/productos/remera-diamond2/",
        "https://www.imanofficial.com/productos/short-diamond5/",
        "https://www.imanofficial.com/productos/vestido-diamond2/",
        "https://www.imanofficial.com/productos/falda-midi-diamond2/",
        "https://www.imanofficial.com/productos/top-corpino-diamond1/",
        "https://www.imanofficial.com/productos/corset-linen6/",
        "https://www.imanofficial.com/productos/top-buche-diamond/",
        "https://www.imanofficial.com/productos/jean-travis/",
        "https://www.imanofficial.com/productos/vestido-melania1/",
        "https://www.imanofficial.com/productos/blazer-dinasty1/",
        "https://www.imanofficial.com/productos/bando-maiden/",
        "https://www.imanofficial.com/productos/blazer-linen2/",
        "https://www.imanofficial.com/productos/camisa-mykonos2/",
        "https://www.imanofficial.com/productos/falda-rock1/",
        "https://www.imanofficial.com/productos/vestido-jessa-corto/",
        "https://www.imanofficial.com/productos/vestido-jessa/",
        "https://www.imanofficial.com/productos/falda-kimy6/",
        "https://www.imanofficial.com/productos/falda-basic1/",
        "https://www.imanofficial.com/productos/camisa-bresh4/",
        "https://www.imanofficial.com/productos/tunica-nomade3/",
        "https://www.imanofficial.com/productos/short-bresh4/",
        "https://www.imanofficial.com/productos/skort-miu/",
        "https://www.imanofficial.com/productos/top-kimy2/",
        "https://www.imanofficial.com/productos/conjunto-bikini-nalu/",
        "https://www.imanofficial.com/productos/conjunto-animal-print/",
        "https://www.imanofficial.com/productos/conjunto-bikini-sunset/",
        "https://www.imanofficial.com/productos/conjunto-bikini-blossom1/",
        "https://www.imanofficial.com/productos/vestido-cat/",
        "https://www.imanofficial.com/productos/vestido-megan1/",
        "https://www.imanofficial.com/productos/blazer-sunset/",
        "https://www.imanofficial.com/productos/vestido-slip-rainbow/",
        "https://www.imanofficial.com/productos/sweater-london5/",
        "https://www.imanofficial.com/productos/jean-mom-shine1/",
        "https://www.imanofficial.com/productos/camisa-wind5/",
        "https://www.imanofficial.com/productos/vestido-kylie3/",
        "https://www.imanofficial.com/productos/conjunto-bikini-faces/",
        "https://www.imanofficial.com/productos/vestido-bali-rainbow/",
        "https://www.imanofficial.com/productos/bando-greek/",
        "https://www.imanofficial.com/productos/giftcard/",
        "https://www.imanofficial.com/productos/short-bresh-rayas/",
        "https://www.imanofficial.com/productos/body-ibiza/",
        "https://www.imanofficial.com/productos/vestido-mykonos-negro/"
    ]
    
data = []
for url in tqdm(urls, desc="Extrayendo datos"):
    product_data = scrape_product(url)
    if product_data:
        data.append(product_data)
    time.sleep(1.5)

if data:
    df = pd.DataFrame(data)
    
    # Exportar a CSV como alternativa simple
    df.to_csv('productos_iman.csv', index=False, encoding='utf-8-sig')
    print(f"\n✅ Datos guardados en productos_iman.csv")
    print(f"📦 Productos extraídos: {len([x for x in data if 'Error' not in x])}/{len(urls)}")
    
    # Intenta exportar a Excel si openpyxl está instalado
    try:
        df.to_excel('productos_iman_detallado.xlsx', index=False)
        print("✅ Versión Excel también generada")
    except:
        print("ℹ️ Instala openpyxl para exportar a Excel: pip install openpyxl")
else:
    print("\n❌ No se pudo extraer ningún dato")